// Centralized MUI imports to reduce bundle size and compilation time
export {
  Container,
  Typography,
  Box,
  Card,
  CardContent,
  Grid,
  Button,
  TextField,
  Alert,
  CircularProgress,
  Chip,
  AppBar,
  Toolbar,
  Drawer,
  List,
  ListItem,
  ListItemButton,
  ListItemText,
  IconButton,
  useTheme,
  useMediaQuery,
} from '@mui/material';

export {
  Email as EmailIcon,
  LocationOn as LocationIcon,
  LinkedIn as LinkedInIcon,
  GitHub as GitHubIcon,
  Send as SendIcon,
  Menu as MenuIcon,
  Close as CloseIcon,
  Home as HomeIcon,
  Person as PersonIcon,
  ContactMail as ContactIcon,
  Schedule as ScheduleIcon,
  AccessTime as TimeIcon,
  VideoCall as VideoCallIcon,
  Business as BusinessIcon,
} from '@mui/icons-material';