[build]
  publish = "dist"
  command = "pnpm run build"

[build.environment]
  NODE_VERSION = "18"
  PNPM_VERSION = "8"

# Production context (main branch)
[context.production]
  command = "pnpm run build"
  
# Branch deploy context (all other branches)
[context.branch-deploy]
  command = "pnpm run build"

# Deploy preview context (pull requests)
[context.deploy-preview]
  command = "pnpm run build"

# SPA redirect rules - ensures React Router works
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"