name = "cloudcodetree-portfolio"
compatibility_date = "2024-01-01"

[env.production]
routes = [
  { pattern = "cloudcodetree.com/*", custom_domain = true }
]

# Pages configuration
pages_build_output_dir = "dist"